name: Backend CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'event_olympia_backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'event_olympia_backend/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: event_olympia_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-and-push:
    name: Build and Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v4
        with:
          context: ./event_olympia_backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/event_olympia_backend:latest

      - name: Log out from Docker Hub
        run: docker logout 